SET search_path TO referentiel, public;

CREATE TABLE IF NOT EXISTS arrondissements (
    code_arrondissement  varchar(4) PRIMARY KEY,
    nom_arrondissement   text        NOT NULL,
    code_postal_prefix   char(5)     NOT NULL
);

CREATE TABLE IF NOT EXISTS services_municipaux (
    service_id           integer     GENERATED BY DEFAULT AS IDENTITY,
    code_service         varchar(64) NOT NULL,
    nom_service          text        NOT NULL,
    type_service         text        NOT NULL,
    arrondissement       varchar(4)  NOT NULL,
    email_contact        text        NOT NULL,
    telephone_contact    varchar(32) NOT NULL,
    est_actif            boolean     NOT NULL DEFAULT true,
    date_creation        timestamp   NOT NULL DEFAULT now(),
    CONSTRAINT pk_services_municipaux PRIMARY KEY (service_id)
);

CREATE TABLE IF NOT EXISTS types_demande_etat_civil (
    code_type_etat_civil varchar(64) PRIMARY KEY,
    libelle              text        NOT NULL
);

CREATE TABLE IF NOT EXISTS types_demande_urbanisme (
    code_type_urbanisme  varchar(64) PRIMARY KEY,
    libelle              text        NOT NULL
);

CREATE TABLE IF NOT EXISTS types_rdv (
    code_type_rdv        varchar(64) PRIMARY KEY,
    libelle              text        NOT NULL
);

CREATE TABLE IF NOT EXISTS canaux_contact (
    code_canal           varchar(32) PRIMARY KEY,
    libelle              text        NOT NULL
);
