SET search_path TO metier, public;

CREATE TABLE IF NOT EXISTS citoyens (
    citoyen_id     integer     GENERATED BY DEFAULT AS IDENTITY,
    nom            text        NOT NULL,
    prenom         text        NOT NULL,
    date_naissance date        NOT NULL,
    email          text        NOT NULL,
    telephone      varchar(32) NOT NULL,
    adresse        text        NOT NULL,
    code_postal    char(5)     NOT NULL,
    ville          text        NOT NULL,
    arrondissement varchar(4)  NOT NULL,
    date_creation  timestamp   NOT NULL DEFAULT now(),
    CONSTRAINT pk_citoyens PRIMARY KEY (citoyen_id)
);

CREATE TABLE IF NOT EXISTS demandes_rdv (
    rdv_id                     integer     GENERATED BY DEFAULT AS IDENTITY,
    citoyen_id                 integer     NOT NULL,
    service_id                 integer     NOT NULL,
    type_rdv                   varchar(64) NOT NULL,
    date_demande               date        NOT NULL,
    date_rdv                   date        NOT NULL,
    statut                     varchar(32) NOT NULL,
    canal                      varchar(32) NOT NULL,
    commentaire                text        NULL,
    rdv_start_ts               timestamp   NULL,
    rdv_end_ts                 timestamp   NULL,
    slot_duration_min          integer     NULL,
    is_peak_hour               boolean     NULL,
    delai_jours_demande_rdv    integer     NULL,
    date_insertion             timestamp   NOT NULL DEFAULT now(),
    CONSTRAINT pk_demandes_rdv PRIMARY KEY (rdv_id)
);

CREATE TABLE IF NOT EXISTS demandes_etat_civil (
    demande_id       integer     GENERATED BY DEFAULT AS IDENTITY,
    citoyen_id       integer     NOT NULL,
    type_demande     varchar(64) NOT NULL,
    date_demande     date        NOT NULL,
    date_traitement  date        NULL,
    statut           varchar(32) NOT NULL,
    mode_retrait     varchar(32) NOT NULL,
    date_insertion   timestamp   NOT NULL DEFAULT now(),
    CONSTRAINT pk_demandes_etat_civil PRIMARY KEY (demande_id)
);

CREATE TABLE IF NOT EXISTS demandes_urbanisme (
    demande_id       integer     GENERATED BY DEFAULT AS IDENTITY,
    citoyen_id       integer     NOT NULL,
    type_demande     varchar(64) NOT NULL,
    adresse_projet   text        NOT NULL,
    code_postal      char(5)     NOT NULL,
    arrondissement   varchar(4)  NOT NULL,
    date_demande     date        NOT NULL,
    date_decision    date        NULL,
    statut           varchar(32) NOT NULL,
    date_insertion   timestamp   NOT NULL DEFAULT now(),
    CONSTRAINT pk_demandes_urbanisme PRIMARY KEY (demande_id)
);
